services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    links:
      - postgres
  postgres:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - '.env.local'
      - '.env.test.local'

volumes:
  postgres:
