require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/stories", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Story. As you add validations to Story, be sure to
  # adjust the attributes here as well.
  let!(:location) {
    Location.create!(address: 'without location story cant be created')
  }

  let(:existing_valid_attributes) {
    {
      address: Location.last.address,
      location: location
    }
  }

  let(:valid_attributes) {
    {
      address: 'valid address name',
      location: location
    }
  }

  let(:invalid_attributes) {
    {
      address: 'shortname',
      location: location
    }
  }

  describe "GET /index" do
    it "renders a successful response" do
      Story.create! valid_attributes
      get root_path
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      story = Story.create! valid_attributes
      get location_story_url(location, story)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_story_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      story = Story.create! valid_attributes
      get edit_location_story_url(location, story)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      context "create a new location" do
        it "creates a new Story" do
          expect {
            post stories_url, params: { story: valid_attributes }
          }.to change(Story, :count).by(1)
        end

        it "creates a new Location after a create Story without existing address" do
          expect {
            post stories_url, params: { story: valid_attributes }
          }.to change(Location, :count).by(1)
        end

        it "redirects to the created new story and creates a new location" do
          post stories_url, params: { story: valid_attributes }
          story_result = Story.last

          expect(response).to redirect_to(location_story_path(story_result.location, story_result))
        end
      end

      context "using existing location location" do
        it "creates a new Story" do
          expect {
            post stories_url, params: { story: existing_valid_attributes }
          }.to change(Story, :count).by(1)
        end

        it "not creating a new location when use existing location address" do
          expect {
            post stories_url, params: { story: existing_valid_attributes }
          }.to change(Location, :count).by(0)
        end

        it "redirects to the created new story and creates a new location" do
          post stories_url, params: { story: existing_valid_attributes }
          created_story = Story.last

          expect(response).to redirect_to(location_story_path(location, created_story))
        end
      end
    end

    context "with invalid parameters" do
      it "does not create a new Story" do
        expect {
          post stories_url, params: { story: invalid_attributes }
        }.to change(Story, :count).by(0)
      end


      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post stories_url, params: { story: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        {
          address: 'changed valid address name'
        }
      }

      it "updates the requested story" do
        story = Story.create! valid_attributes
        patch story_url(story), params: { story: new_attributes }
        story.reload
        expect(story.address).to eq(new_attributes[:address])
      end

      it "redirects to the story" do
        story = Story.create! valid_attributes
        patch story_url(story), params: { story: new_attributes }
        story.reload
        expect(response).to redirect_to(story_url(story))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        story = Story.create! valid_attributes
        patch story_url(story), params: { story: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested story" do
      story = Story.create! valid_attributes
      expect {
        delete story_url(story)
      }.to change(Story, :count).by(-1)
    end

    it "redirects to the stories list" do
      story = Story.create! valid_attributes
      delete story_url(story)
      expect(response).to redirect_to(stories_url)
    end
  end
end
